[package]
name = "svgcode"
version = "0.1.0"
authors = ["José Luis C.D. <jlcd0003@red.ujaen.es>"]
edition = "2018"

[dependencies]
cgmath = "^0.18"
usvg = "^0.7"
lyon_path = "^0.14"
clap = { version = "^4.5", features = ["derive"] }
